### ISSUE TITLE
Datenbank initialisieren

### ISSUE THREAD

**Issue by spegenau** [Data-City/admin-tool#10]
Es soll möglich sein, über ein Befehl - beispielsweise grunt initDB - eine neue, leere Datenbank zu initialisieren.

Dazu ist es nötig:
- Die Nutzer zu hinterlegen (Siehe Übergabekonzept 3.1 MongoDB - zweiter Punkt)
- Die Collection **Ansichten** anzulegen

Ggf. sind weitere Schritte nötig, aber das wäre ein Anfang.

**Comment by ZiZiWang** [comment]
Meiner Meinung nach braucht man nicht allen Datenbanken zu initialisieren. Wir brauchen nur die Datenbank einstellungen und prelife zu löschen und noch eine neuen Datenbank zu initialisieren.
 var initData = function () {
        var removeEinstellungenCmd = 'mongo einstellungen --eval "db.dropDatabase()"'
        var removePrelifeCmd = 'mongo prelife --eval "db.dropDatabase()"'
    var removeEinstellungen = shell.exec(removeEinstellungenCmd);
    var removePrelife = shell.exec(removePrelifeCmd);
    var addAnsichtenCmd = 'mongo einstellungen --eval "db.createCollection("ansichten")"'
    var addAnsichten = shell.exec(addAnsichtenCmd);
}

module.exports = function (grunt) {
    grunt.registerTask('initData', initData());}

Aber Anlegen einer Collection Ansichten wurde nicht realisiert.

**Comment by Nullmann** [comment]
Es gibt eine "initData.bat" in dem Windows Paket. Ist das die Datei und kann der Issue damit geschlossen werden?

**Comment by spegenau** [comment]
Nicht, wenn die Initialisierung immer noch mit einem vbs-Skript läuft.
