### ISSUE TITLE
Import der Datei mit der Verbindungen

### ISSUE THREAD

**Issue by ZiZiWang** [Data-City/admin-tool#13]
Es funktioniert bei mir weder local noch Server. Nach dem Import bleibt der ImportStatus immer bei 100% und kein finishmsg wird angezeigt. In der DB wurde keine Verbindungsmetadatei nach dem Import generiert, deswegen kann man keine Verbindungen bei der Ansichtseinstellung auswählen.

**Comment by Nullmann** [comment]
Wenn ich Steffens Commit richtig interpretiere, ist das auch noch gar nicht implementiert.

![screenshot 2016-03-05 00 00 30](https://cloud.githubusercontent.com/assets/15816473/13542763/669144bc-e265-11e5-9b8b-c581336dfa3c.png)

**Comment by JuliaH1** [comment]
@SteffenPegenau bei mir passiert das gleiche. Es wird alles richtig importiert, auch die Verbindungsdateien, nur werden sie nicht aggregiert... Dieser Fehler wird bei mir angezeigt
![adminfehler](https://cloud.githubusercontent.com/assets/15839253/13549871/06f21d00-e310-11e5-94cc-ce9d4f210cc3.png)
Datensatz TestJulia zeigt dieses Problem auf. Da kann man auch die Verbindungen auswählen und die Dreiecke werden auch gezeichnet, aber keine Straßen/Bögen entstehen, wenn man drauf klickt

**Comment by ManuelMueller1988** [comment]
Same here
