### ISSUE TITLE
Task definieren: Import einer CSV-Datei

### ISSUE THREAD

**Issue by spegenau** [Data-City/admin-tool#2]
Was auf dem Server im Moment das Linux-Shell Skript import macht, soll durch grunt erledigt werden.

**Comment by Nullmann** [comment]
Dafür gibt es ein [grunt-plugin!](https://www.npmjs.com/package/mongobackup)

Läuft allerdings nicht auf Windows:

> As this plugin depends on the node child_process module and the spawn method, it doesn't yet support Windows systems.
